spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/terminalv2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: terminaladmin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    open-in-view: false

      #swagger ??? ant_path_matcher? ??
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

file:
  dir: /Users/ganghyeog/desktop/files/

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

